version: '3'

services:

  cat_shop:
    build: ./
    container_name: cat_shop
    environment:
      FLASK_DEBUG: True
      DB_NAME: cat_shop
      DB_USERNAME: postgres
      DB_PASSWORD: YOUR_PG_PASSWORD
      DB_PORT: 5432
      DB_HOST: pgsql
    volumes:
      - ./:/cat_shop
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    image: postgres:13.0-alpine
    container_name: pgbd2
    environment:
      POSTGRES_PASSWORD: YOUR_PG_PASSWORD
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
